# Generated by Django 5.2.3 on 2025-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MOPDIC', max_length=255, verbose_name='Site Name')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('site_logo', models.ImageField(blank=True, help_text='Recommended size: 200x50 pixels', null=True, upload_to='site/', verbose_name='Site Logo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_address', models.TextField(blank=True, verbose_name='Contact Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Format: UA-XXXXXXXXX-X or G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
