services:
  - type: web
    name: mopdic
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn mopdic.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2  # Reduced for SQLite
      - key: ALLOWED_HOSTS
        value: 'mopdic.onrender.com,localhost,127.0.0.1'
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: PYTHONPATH
        value: '$PYTHONPATH:/opt/render/project/src'
      - key: IS_RENDER
        value: 'yes'
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /admin/
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1
