services:
  - type: web
    name: mopdic
    env: python
    buildCommand: "chmod a+x build.sh && ./build.sh"
    startCommand: "gunicorn mopdic.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: 'mopdic.onrender.com,localhost,127.0.0.1'
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: PYTHONPATH
        value: '$PYTHONPATH:/opt/render/project/src'
      - key: IS_RENDER
        value: 'yes'
    plan: free  # or 'standard' for production
    autoDeploy: true
    region: oregon  # Choose the region closest to your users
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mopdic-db
          property: connectionString

# Uncomment and configure when you set up a database
# databases:
#   - name: mopdic-db
#     databaseName: mopdic
#     user: mopdic_user
#     plan: free  # or 'standard' for production
