# Generated by Django 5.2.3 on 2025-06-28 18:13

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_document_options_project_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='A descriptive title for the file', max_length=255)),
                ('file', models.FileField(help_text='The actual file to upload', upload_to=main.models.get_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='other', help_text='Type of the file (auto-detected on save)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image/video width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image/video height in pixels', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Duration for audio/video files', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type', max_length=100)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the file is publicly accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_media', 'Can manage media files')],
            },
        ),
    ]
