# Generated by Django 5.2.3 on 2025-06-29 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='file',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish_date')),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/%d/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-publish_date'],
            },
        ),
    ]
