# Generated by Django 5.2.3 on 2025-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
